---
title: "Post One"
description: |
  Senior Project Proposal 
author:
  - name: Eden Sheffer
    url: https://example.com/norajones
date: 2021-10-4
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Personal Background Hi

I have completed MATH 425. I am undecided in what career field I am most interested 
in. Currently, I am searching for internships and hope for employment where I intern. I 
am most interested in business and consulting. I love helping people!

Project Background

I know a professor who is the CEO of Hero Hub. This company is growing quickly and is
making deals with large businesses such as Polaris. They are looking to innovate and 
grow their business. A mass survey is being sent out and they are expecting thousands 
of responses. (This survey is expected to be completed in September. I am waiting to 
hear back from the professor.) The big question is what areas does Hero Hub need to 
focus on to continue their growth?

Domain to Investigate

I would be using Qualtrics information from Hero Hub. I could also do additional 
research on companies to compare their results with Hero Hub. 

Proposed Deliverables

• Find/predict trends
• Clean up survey data (practice wrangling)
• Find trends that could help in future decisions
• Create insightful easy to read graphics



